### ISSUE TITLE
deletes fontawesome tag

### ISSUE THREAD

**Issue by rcsmit** [AnWeber/vscode-tidyhtml#24]
This TidyHTML deletes fontawesomtages like ` <i  aria-hidden="true"  class="fas fa-linkedin"></i>`

Lost 1 hour due to this, deleted the extension, no trust anymore, sorry.

**Comment by AnWeber** [comment]
Sorry to hear that. I suspect that the cause is the setting [drop-empty-elements](https://api.html-tidy.org/tidy/quickref_5.8.0.html#drop-empty-elements) (default: yes). Empty tags that should have content are removed (https://github.com/htacg/tidy-html5/issues/669).

I also don't use tidy-html myself anymore either, because I really only want formatting, but [tidy-html](https://www.html-tidy.org/) always does validation/ dropping as well. For that reason there have been no updates for a long time.
